const sets = [
[
{title:'A different kind of school day',tag:'Community · Personal story',text:`When Maya arrived at her new school in Ohio, she expected the hardest part to be understanding her teachers. In fact, lessons were easier than she had imagined. It was lunchtime that made her nervous. Everyone seemed to know where to sit and who to talk to. For the first week, she ate quickly and spent the rest of the break in the library.

One afternoon, the librarian asked whether Maya would help with a Saturday book sale. Maya almost refused because she had never worked at an event in English. However, the librarian explained that she would work with another student, Ben. Their job was to sort donated books and put price labels on them. While they worked, they discovered that they both enjoyed mystery stories.

On Saturday, very few visitors came during the first hour. Ben suggested lowering all the prices, but Maya thought the problem was that people did not know about the sale. With the librarian's permission, they moved a small table of books outside the entrance. Soon, people stopped to look and then went inside. By the end of the day, the sale had raised enough money to buy new reading chairs.

The following Monday, Ben invited Maya to sit with his friends at lunch. She still sometimes needed people to repeat a sentence, but she no longer felt that she had to speak perfectly before joining a conversation. Looking back, she said the book sale had given her something more valuable than language practice: a reason to talk to people.`,q:[
['What was most difficult for Maya at first?',['Understanding lessons','Finding books','Feeling comfortable at lunch','Travelling to school'],2,'В первом абзаце сказано, что именно обед вызывал тревогу.'],
['Why did Maya nearly refuse to help?',['She lacked confidence using English at an event','She disliked Ben','She had a lesson on Saturday','She did not enjoy reading'],0,'Она никогда не работала на мероприятии на английском и сомневалась.'],
['What did Maya and Ben have in common?',['They were new students','They liked mystery stories','They wanted to become librarians','They had worked at sales before'],1,'Они выяснили, что оба любят детективные истории.'],
['Why did they move some books outside?',['There was no space indoors','The chairs had arrived','The librarian wanted lower prices','They wanted to attract attention'],3,'Майя считала, что люди просто не знают о распродаже.'],
['In the text, “raised” means…',['collected','lifted','borrowed','counted'],0,'Raise money — собрать деньги.'],
['What is the main message of the story?',['Perfect English is necessary for friendship','Libraries are better than classrooms','A shared activity can help someone connect with others','Book sales always make a large profit'],2,'Совместное дело дало Майе повод общаться и помогло найти друзей.'] ]},
{title:'The repair café',tag:'Everyday life · Article',text:`On the first Sunday of every month, a room in Westbridge Community Centre becomes a repair café. Visitors bring broken lamps, torn jackets and small household objects. Volunteers try to repair them while their owners watch and, when possible, help. There is no fixed charge, although donations pay for basic materials.

The café was started by a retired engineer, Daniel Price. He noticed that neighbours were throwing away objects with minor problems. At first, he thought the main benefit would be less waste. After several months, however, he realised that visitors valued the conversations just as much as the repairs. Some older residents began coming even when they had nothing broken to bring.

Not every object can be repaired. Volunteers refuse items that could be unsafe, and sometimes a replacement part costs more than the object itself. The organisers therefore ask visitors not to expect a guaranteed repair. They also explain that the café is not a free professional repair shop: learning together matters more than finishing quickly.

Last month, a teenager named Ella brought a jacket with a broken zip. Instead of fixing it for her, a volunteer showed her how to replace the zip herself. It took most of the afternoon. Ella said she could have bought a cheap new jacket in less time, but now she had a skill she could use again. Daniel sees experiences like hers as evidence that the café is working. He hopes to recruit more volunteers, especially people who can repair bicycles, but he does not plan to make the café a weekly event yet.`,q:[
['How often does the café take place?',['Every Sunday','Once a month','Twice a week','Every afternoon'],1,'Встреча проходит в первое воскресенье каждого месяца.'],
['What originally motivated Daniel?',['Selling replacement parts','Teaching teenagers only','Creating a paid repair business','Reducing unnecessary waste'],3,'Сначала главной пользой он считал уменьшение отходов.'],
['What surprised Daniel about visitors?',['They also valued social contact','They preferred new objects','They refused to watch repairs','They all wanted to volunteer'],0,'Посетители ценили разговоры не меньше, чем ремонт.'],
['Why might volunteers refuse an item?',['Its owner is too young','It was bought recently','It could be dangerous','It is not expensive'],2,'В тексте прямо указано: небезопасные вещи не принимают в ремонт.'],
['What did Ella gain from the visit?',['A free new jacket','An ability she could use in the future','A job at the centre','A faster way to shop'],1,'Элла научилась менять молнию — этот навык пригодится снова.'],
['Which statement matches Daniel’s current plans?',['Open every week immediately','Stop accepting clothing','Charge every visitor','Find volunteers with bicycle repair skills'],3,'Он ищет дополнительных волонтёров, особенно умеющих чинить велосипеды.'] ]},
{title:'When a shortcut is not faster',tag:'Ideas · Science & society',text:`A city transport team recently tested a simple idea: could better information encourage more people to walk? Many residents drove between the central station and a shopping street because they believed the walk took at least twenty minutes. The actual journey on foot was usually eight minutes. Driving could take longer once finding a parking space was included.

The team placed signs at important junctions. Instead of showing only distances, each sign gave the approximate walking time to familiar places. The signs also pointed out routes through public gardens. During a six-week trial, the number of people walking from the station to the shopping street increased. Interviews suggested that the time estimates helped people reconsider their usual choices.

However, the researchers were careful about their conclusions. The trial took place in spring, when the weather was unusually pleasant. A new café also opened near the walking route during the same period. Either change might have encouraged walking independently of the signs. To understand the signs' effect more clearly, the team plans to compare similar areas with and without them during the same months.

The project also revealed a limitation of simple time estimates. A route described as an eight-minute walk may take considerably longer for someone with limited mobility. After receiving feedback, the team added information about steps and steep slopes to its online map. The researchers argue that useful travel information should not tell everyone what to do. Instead, it should help different people make decisions that suit their circumstances.`,q:[
['Why did many residents choose to drive?',['Walking was forbidden','They overestimated the walking time','The station had moved','There were no public gardens'],1,'Жители думали, что идти не меньше 20 минут, хотя обычно путь занимал 8.'],
['What was distinctive about the signs?',['They advertised parking','They showed only distances','They gave estimated walking times','They recommended one café'],2,'На указателях было примерное время пешего пути.'],
['What happened during the trial?',['More people walked along the studied route','All residents stopped driving','Parking became free','The shopping street closed'],0,'Количество пешеходов на изучаемом маршруте выросло.'],
['Why were the researchers cautious?',['Nobody read the signs','They had lost their results','The trial lasted several years','Other changes could have affected walking'],3,'Хорошая погода и новое кафе могли повлиять на результат отдельно от указателей.'],
['What does “them” in “with and without them” refer to?',['Researchers','Signs','Gardens','Interviews'],1,'Планируется сравнить похожие районы с указателями и без них.'],
['What is the author’s main conclusion?',['Everyone should walk at the same speed','Time estimates should replace all maps','Information should support people with different needs','Driving is always slower than walking'],2,'Информация должна помогать разным людям выбирать с учётом своих обстоятельств.'] ]}
],
[
{title:'Learning to listen',tag:'Exchange life · Personal story',text:`During his first month with a host family, Anton tried to say yes to every invitation. He joined the school running club, helped prepare a neighbourhood picnic and agreed to play a small part in a drama performance. He wanted to make the most of his exchange year. Soon, though, he was doing homework late at night and arriving at breakfast exhausted.

His host sister, Rachel, noticed that he had stopped enjoying the activities he had chosen. When she asked what was wrong, Anton admitted that he was afraid people would think he was unfriendly if he turned down an invitation. Rachel explained that saying no politely was normal. She suggested that he choose two activities he really cared about and leave some evenings free.

Anton decided to continue running and acting, but told the picnic organiser that he could help for one hour rather than the whole afternoon. The organiser thanked him for being clear about his availability. Nobody seemed offended. With a more manageable schedule, Anton began to enjoy conversations instead of worrying about his next commitment.

Several weeks later, a new student asked Anton how to become involved in school life. Anton did not advise him to accept every opportunity. Instead, he suggested trying a few activities and then deciding which ones felt worthwhile. He had learned that participating fully did not mean being busy every minute. Sometimes, making space in his schedule helped him pay more attention to the people around him.`,q:[
['Why did Anton initially accept every invitation?',['He wanted to use his exchange year well','His teachers required it','He disliked being at home','He wanted to avoid homework'],0,'Он хотел получить максимум от года по обмену.'],
['What was a consequence of his schedule?',['He left the school','He slept too much','He became exhausted','He stopped studying entirely'],2,'Он поздно делал домашнюю работу и приходил к завтраку уставшим.'],
['What worried Anton about refusing invitations?',['Losing a competition','Appearing unfriendly','Paying a fee','Missing his flight'],1,'Он боялся, что отказ сочтут недружелюбным.'],
['How did the picnic organiser react?',['Asked him to leave the club','Cancelled the picnic','Was offended','Appreciated his clear explanation'],3,'Организатор поблагодарил его за ясность насчёт свободного времени.'],
['“Manageable” describes a schedule that is…',['impossible to change','easier to handle','completely empty','the same for everyone'],1,'Manageable — такой, с которым можно справиться.'],
['What did Anton learn?',['All invitations should be refused','School clubs waste time','Meaningful participation requires balance','Being busy guarantees friendship'],2,'Участие приносит больше пользы, когда нагрузка сбалансирована.'] ]},
{title:'A library beyond books',tag:'Community · Article',text:`The small library in Northfield has started lending objects as well as books. Members can borrow items such as a sewing machine, a camping tent or a set of gardening tools. The idea came from a survey in which residents said they sometimes needed expensive equipment for only one or two days. Buying it seemed wasteful, especially for people living in small flats.

Before launching the service, library staff asked local organisations to donate equipment. They accepted only items in good condition that were easy to inspect. Each object comes with instructions, and borrowers must attend a short demonstration before taking certain items home. The normal loan period is one week. Objects cannot be renewed online because staff need to check them between loans.

The most popular item has been a carpet cleaner. Staff expected camping equipment to attract the most interest, but demand for it has been seasonal. The carpet cleaner, by contrast, is booked throughout the year. To avoid long waiting lists, the library has recently purchased a second one using money from a community grant.

Some residents worried that the new service would take money away from books. The library manager says the equipment budget is separate and that book purchases have not been reduced. She also reports that several people who first visited to borrow tools have since become regular readers. The library will review the service after a year before deciding whether to expand it.`,q:[
['What need did the survey identify?',['More private storage rooms','Short-term access to costly equipment','Longer camping holidays','Free equipment to keep forever'],1,'Жителям нужны были дорогие вещи всего на день-два.'],
['Which donated items were accepted?',['Anything that was large','Only brand-new objects','Items in good condition that were easy to check','Only gardening equipment'],2,'Принимали исправные вещи, которые легко осматривать.'],
['Why are online renewals unavailable?',['Staff must inspect objects between loans','The library has no website','All loans last one day','Borrowers must buy used items'],0,'Перед следующим займом сотрудники должны проверить вещь.'],
['What surprised staff?',['Nobody borrowed tools','Books became unavailable','Tents were used all year','The carpet cleaner was the most popular'],3,'Ожидали большего спроса на походное снаряжение, но лидером стал аппарат для чистки ковров.'],
['How was the second carpet cleaner funded?',['Through higher book prices','With a community grant','By selling the first one','Through compulsory donations'],1,'В тексте указано финансирование через общественный грант.'],
['What does the manager say about books?',['They will be replaced by equipment','They can no longer be borrowed','Their purchasing budget has not been cut','Only tool borrowers may read them'],2,'Покупки книг не сократили: бюджет оборудования отдельный.'] ]},
{title:'The value of getting lost',tag:'Ideas · Research',text:`Digital navigation makes unfamiliar journeys easier, but some researchers wonder whether following every instruction affects how well we learn a place. In a small study, volunteers explored a neighbourhood they had never visited. One group followed spoken directions from a phone. Another used a paper map and chose its own route to the same destination.

The phone users generally arrived sooner and made fewer wrong turns. Later, however, the map users were better at recognising landmarks and describing how streets connected. The researchers suggest that choosing a route encourages people to pay attention to their surroundings, while step-by-step directions can allow them to focus mainly on the next instruction.

This does not mean that digital navigation is harmful or that paper maps are always better. Participants differed in their previous experience with maps, and the study involved only a small number of adults in one neighbourhood. A larger study would be needed to know whether the same pattern appears in other settings. Navigation tools can also be especially useful for people who would otherwise find unfamiliar travel stressful.

Rather than abandoning their phones, the researchers suggest that travellers sometimes pause to notice a landmark or predict the next turn before checking the screen. Such small changes might combine the convenience of digital help with more active learning. The important question, they argue, is not which tool is best in every situation, but how people use the tools available to them.`,q:[
['What did the study compare?',['Two different cities','Adults and children','Different ways of navigating an unfamiliar area','Walking and cycling speeds'],2,'Сравнивали навигацию по голосовым инструкциям и самостоятельный выбор пути по карте.'],
['Which group usually reached the destination sooner?',['Phone users','Map users','Both always arrived together','The text does not say'],0,'Пользователи телефона обычно приходили быстрее.'],
['What were map users better at afterwards?',['Remembering phone numbers','Finding the shortest route home','Using spoken directions','Recognising landmarks and street connections'],3,'Они лучше узнавали ориентиры и описывали связи между улицами.'],
['Which limitation is mentioned?',['Every participant was a child','Only a small number of adults took part','No one reached the destination','The routes were in different countries'],1,'Исследование небольшое: мало взрослых участников и один район.'],
['What do researchers recommend?',['Never carrying a phone','Ignoring all road signs','Noticing surroundings while using digital help','Always choosing the longest route'],2,'Совет — замечать ориентиры и предугадывать поворот, продолжая пользоваться телефоном.'],
['What best describes the writer’s attitude?',['Balanced and cautious','Entirely opposed to technology','Certain that maps always win','Uninterested in the evidence'],0,'Автор показывает и пользу телефона, и ограничения исследования, не делает категоричных выводов.'] ]}
]
];

sets.push(
[
{title:'The interview that changed',tag:'School life · Personal story',text:`Leila joined the school newspaper because she loved writing, but her first assignment made her uncomfortable. She had to interview the caretaker, Mr Harris, about his thirty years at the school. She prepared ten questions about broken windows and cleaning schedules. She expected a short conversation with very little to write about.

When they met, Mr Harris showed her a photograph of the school garden. It had once been an empty yard. He explained how students had helped him plant trees there after a storm damaged the old fence. Leila put her prepared questions aside and asked who had taken part. Soon he was telling her about students who returned years later to see the trees they had planted.

Her first draft contained every detail of the conversation. The editor asked her to choose one central idea instead. Leila was disappointed, but eventually focused on how the garden connected different generations of students. She checked the dates with Mr Harris before submitting the revised article.

The finished piece received more responses than she expected. Several former students sent photographs of the planting day. Leila realised that preparation was useful, but a good interview also required noticing when an unexpected story was worth following.`,q:[
['What did Leila initially expect?',['An exciting travel story','A conversation with little interesting material','An argument about the newspaper','A lesson in photography'],1,'Она ожидала короткий разговор, о котором почти нечего написать.'],
['What caused her to change her questions?',['A photograph and the story behind it','A call from the editor','A broken window','A missing notebook'],0,'Фотография сада привела к неожиданной истории о его создании.'],
['Why did former students return?',['To repair the fence','To apply for work','To collect newspapers','To see trees they had planted'],3,'Мистер Харрис рассказал о выпускниках, возвращавшихся посмотреть на свои деревья.'],
['What did the editor ask her to do?',['Add more dates','Remove all quotations','Focus on one main idea','Interview a different person'],2,'Редактор попросил выбрать одну центральную мысль.'],
['What does “revised” mean here?',['Written in another language','Changed and improved','Published without checking','Copied from a photograph'],1,'Revised article — переработанная статья; Лейла сузила тему и проверила даты.'],
['What is the main lesson of the story?',['Stay open to unexpected information','Avoid preparing questions','Publish every detail you hear','Interview only famous people'],0,'Подготовка важна, но нужно уметь заметить неожиданную интересную тему.'] ]},
{title:'Dinner without a menu',tag:'Community · Article',text:`Every Thursday, volunteers at a community kitchen prepare dinner from food that local shops cannot sell the next day. A delivery might include perfectly good vegetables with unusual shapes or bread baked that morning. Because the ingredients change each week, the cooks cannot announce a menu in advance.

The kitchen welcomes everyone. Guests may pay what they can, including nothing, and they all sit at the same long tables. The organisers deliberately avoid separate queues for people who pay and those who do not. They want dinner to feel like a neighbourhood gathering rather than a service divided into groups.

The project has faced practical problems. During its first month, deliveries sometimes arrived too late to prepare the advertised number of meals. The team now keeps a small supply of rice and beans, bought with donations, as a backup. Volunteers also check food carefully and follow the kitchen's safety procedures; receiving an item for free does not automatically make it suitable to serve.

The organisers measure success in more than meals. Guests have started exchanging recipes and offering one another help with everyday tasks. Although reducing waste remains important, the team believes that building relationships is an equally valuable result.`,q:[
['Why is there no advance menu?',['Guests must bring their own meals','The cooks dislike planning','Available ingredients vary','The kitchen opens without staff'],2,'Состав поставок меняется каждую неделю, поэтому меню заранее неизвестно.'],
['Who may eat at the kitchen?',['Only shop employees','Only people who donate','Only invited neighbours','Anyone, regardless of ability to pay'],3,'Приходить могут все, в том числе те, кто не может заплатить.'],
['Why are there no separate queues?',['To create a shared social experience','To hide the number of guests','To sell meals more quickly','To avoid checking ingredients'],0,'Организаторы хотят общего соседского ужина без разделения людей по оплате.'],
['What problem does the backup supply address?',['Too many recipes','Late or insufficient deliveries for planned meals','A lack of dining tables','Expensive restaurant menus'],1,'Запас риса и фасоли помогает готовить, когда поставки приходят слишком поздно.'],
['Which statement about donated food is supported?',['It is always safe','It must always be bread','It still needs to be checked','It can only be served cold'],2,'Бесплатные продукты всё равно тщательно проверяют.'],
['What additional benefit do organisers value?',['Longer shopping hours','More separate dining areas','Fewer volunteers','Stronger relationships between guests'],3,'Общение переросло в обмен рецептами и взаимопомощь.'] ]},
{title:'A quieter experiment',tag:'Ideas · Research',text:`At Brookside School, a teacher noticed that students disagreed about background music during independent work. Some said it helped them concentrate; others found it distracting. Rather than hold a vote, she invited the class to investigate the question during four short reading sessions.

Two sessions took place with quiet instrumental music and two without music. Students answered questions about each text and rated how focused they felt. The teacher alternated the conditions instead of placing all the silent sessions first. She also tried to choose texts of similar length and difficulty.

The results were mixed. Students often reported enjoying the music, but enjoyment did not always correspond to more correct answers. Several students performed better in silence, while others showed little difference. One student pointed out that being unfamiliar with a text's topic could affect scores as much as the room's sound.

The teacher did not claim that the activity proved which environment was best for everyone. The class was small, and four sessions could not represent every kind of schoolwork. Instead, they agreed to keep shared reading periods quiet and allow headphones during certain individual creative tasks. The experiment helped them discuss their needs using observations rather than assuming that everyone worked in the same way.`,q:[
['Why did the teacher organise the activity?',['To choose a school song','To investigate different views about music','To replace reading lessons','To select the best musician'],1,'Ученики по-разному оценивали влияние музыки, и учитель предложила это изучить.'],
['What did students record besides answers?',['Their feelings about concentration','Their favourite instruments','Their journey times','Their homework schedules'],0,'Они оценивали, насколько сосредоточенными себя чувствовали.'],
['What did the results suggest?',['Music helped every student','Enjoyment guaranteed accuracy','Silence prevented learning','Enjoying music did not necessarily improve scores'],3,'Музыка могла нравиться, но это не всегда означало больше правильных ответов.'],
['What other influence did a student mention?',['Classroom temperature','The price of headphones','Familiarity with the topic','The length of the school year'],2,'Знакомство с темой текста тоже могло влиять на результат.'],
['Why were the conclusions limited?',['No one completed the tasks','The activity involved few students and sessions','The music was always loud','Only creative tasks were tested'],1,'Небольшой класс и четыре занятия не позволяют делать выводы обо всей учёбе.'],
['What was agreed for shared reading?',['It would take place in silence','Everyone would wear headphones','Students would choose songs together','It would be replaced by drawing'],0,'Общие периоды чтения решили проводить в тишине.'] ]}
],
[
{title:'The bus stop project',tag:'Community · Personal story',text:`When Noah began taking the bus to school, he noticed that the timetable at his stop was difficult to read. Rain had faded the paper, and a large advertisement covered part of it. He assumed someone had already reported the problem, but after several weeks nothing changed.

For a class project, Noah decided to investigate. He spoke to passengers at three nearby stops and discovered that many had similar complaints. One older passenger explained that checking an app was not an option because she did not own a smartphone. Noah had initially planned to suggest replacing paper timetables with a digital code, but this conversation changed his proposal.

He sent the transport office photographs of the damaged signs and a short summary of passenger comments. Instead of demanding a new app, he asked for large, weather-resistant timetables with a phone number for service information. The office replied that it could not replace every sign immediately, but agreed to test the design at two stops.

A month later, Noah visited the stops again. The new signs were easier to read, although one had been installed too high for some passengers. He included that issue in his follow-up report. He was pleased with the improvement, but understood that a useful project did not end as soon as the first change was made.`,q:[
['What initially prevented Noah from acting?',['He believed someone had already reported it','He never used the stop','He worked for the bus company','He could not find the stop'],0,'Он предполагал, что о проблеме уже сообщили.'],
['Why did he reconsider using a digital code?',['Codes were too expensive','His teacher banned phones','Some passengers could not use smartphones','The timetable had no numbers'],2,'Разговор с пассажиркой без смартфона показал ограничение цифрового решения.'],
['What evidence did Noah send?',['Bus tickets only','Photographs and passenger comments','A list of phone brands','A new app'],1,'Он отправил фото повреждённых указателей и краткое изложение отзывов.'],
['What did the office agree to do?',['Replace every stop at once','Remove all paper timetables','Cancel the route','Test new signs at two stops'],3,'Транспортная служба согласилась на пробное внедрение на двух остановках.'],
['What remained wrong with one new sign?',['It showed another town','It was placed too high','It lacked weather protection','It was hidden by a tree'],1,'Один указатель установили слишком высоко для части пассажиров.'],
['What does the ending emphasise?',['Only apps can solve transport problems','Feedback is unnecessary after a change','Improvements should be checked after implementation','Passengers always agree'],2,'После внедрения нужно проверять, насколько решение удобно людям.'] ]},
{title:'A museum you can touch',tag:'Culture · Article',text:`Visitors to the Eastbank Museum are usually asked not to touch the objects on display. However, a new weekend session takes a different approach. In a small learning room, trained guides invite visitors to handle selected objects and carefully made copies. The museum hopes the sessions will make history accessible through more than sight alone.

The programme began after a local group of visitors with visual impairments suggested ways to improve their experience. Staff first considered providing longer audio descriptions. During discussions, however, they learned that some details, such as an object's weight or the texture of a handle, were easier to understand through touch.

Not every object can be used. Fragile items remain in their cases, and guides explain clearly which pieces are original and which are copies. A copy of a cooking pot, for example, allows visitors to explore its shape without damaging the original. Sessions are kept small so that everyone has time to ask questions.

The museum originally expected the programme to appeal mainly to people with limited vision. Instead, families and other visitors also began booking places. Staff now see it as an additional way to learn, rather than a replacement for ordinary exhibitions. They plan to collect feedback before deciding whether to offer sessions during the week.`,q:[
['What is different about the new sessions?',['All exhibits are taken outdoors','Visitors may handle selected objects','Guides are not present','Visitors must bring historical objects'],1,'Можно брать в руки специально выбранные предметы и копии.'],
['Who helped inspire the programme?',['Visitors with visual impairments','A cooking company','School sports teams','International tourists only'],0,'Программу предложили развить посетители с нарушениями зрения.'],
['Which feature is particularly suited to touch?',['An object’s date','The name of its owner','Its photograph','Its weight and texture'],3,'Вес и фактуру легче почувствовать руками, чем понять из описания.'],
['Why are copies used?',['They require no explanation','They are always older','They protect fragile originals from damage','They can be sold after each session'],2,'Копии позволяют изучить форму, не повреждая оригиналы.'],
['Why are groups small?',['The museum is closing','Each visitor needs time to participate','Only staff may attend','Few people are interested'],1,'Небольшая группа даёт каждому возможность исследовать предметы и задать вопросы.'],
['How do staff now view the programme?',['As another useful way to learn','As a substitute for every exhibition','As unsuitable for families','As a project that has already ended'],0,'Это дополнительный способ изучения, а не замена обычным выставкам.'] ]},
{title:'The missing half of the survey',tag:'Ideas · Critical thinking',text:`A student council wanted to know whether the school should open its sports hall before lessons. It posted an online survey in the running club's group chat. Within two days, thirty students replied, and twenty-seven supported the idea. The council prepared a headline saying that ninety percent of students wanted earlier opening hours.

Before the report was published, a mathematics teacher asked who had received the survey. Most respondents already belonged to a sports club and regularly arrived early for training. Students who travelled on later buses or had little interest in sport were unlikely to have seen the questions. The calculation was correct, the teacher explained, but the headline described a much larger group than the survey had actually reached.

The council repeated the survey during class registration across every year group. Support for early opening remained, but it was less widespread than the first results suggested. Several students preferred later afternoon access instead. Others liked the idea in principle but said they would rarely use the hall themselves.

The final report included these differences and stated how the answers had been collected. The council still recommended a short trial, but no longer claimed to represent an almost unanimous opinion. The experience showed that useful evidence depends not only on counting responses, but also on considering whose voices are missing.`,q:[
['Where was the first survey shared?',['In every classroom','On a public street','In a running club chat','At a parents’ meeting'],2,'Первый опрос разместили только в чате бегового клуба.'],
['What was wrong with the original headline?',['The percentage calculation was incorrect','It understated the number of replies','It described a different sport','It generalised beyond the group surveyed'],3,'90% вычислены верно, но это доля ответивших из клуба, а не всех учеников.'],
['Who was unlikely to see the first survey?',['Students outside the sports group','The club’s regular runners','Students already training early','The people who posted it'],0,'Ученики вне спортивной группы могли вообще не увидеть опрос.'],
['What changed in the second survey?',['Only teachers answered','Students across all year groups were reached','All questions were removed','Only early bus passengers answered'],1,'Второй опрос провели в классах всех возрастных параллелей.'],
['What distinction appeared in the responses?',['All support meant daily use','Nobody preferred afternoon access','Supporting the idea did not always mean planning to use it','Every year group gave identical answers'],2,'Некоторым идея нравилась, но сами они редко стали бы пользоваться залом.'],
['What is the central message?',['Small surveys are always useless','Headlines should avoid numbers','Sport should be compulsory','Consider who is represented in the evidence'],3,'Важно понимать, чьи мнения попали в данные, а чьи отсутствуют.'] ]}
],
[
{title:'Behind the microphone',tag:'School life · Personal story',text:`Sofia volunteered to present her school's weekly audio programme because she wanted to become more confident speaking English. For her first episode, she wrote a detailed script about an upcoming science fair. She practised until she could read every sentence without hesitation. During the recording, however, her voice sounded flat and hurried.

Her classmate Amir, who managed the recording equipment, suggested that she imagine explaining the event to one friend. He also asked her to replace several long sentences with shorter ones. Sofia worried that simpler language would make the programme sound less serious, but agreed to record a second version.

When they listened to both recordings, the difference was clear. The second was easier to follow, even though Sofia paused occasionally. They kept a short pause before the registration deadline so listeners would notice it. Before publishing, Sofia checked the deadline with the science teacher and corrected a date in her script.

A student later told her that the episode had persuaded him to enter the fair because the instructions were clear. Sofia had expected confidence to mean speaking quickly and never stopping. She now understood that helping listeners follow her ideas mattered more than sounding flawless. For her next episode, she prepared key points as well as a full script, leaving room for a more natural delivery.`,q:[
['Why did Sofia volunteer?',['To avoid the science fair','To improve her speaking confidence','To repair audio equipment','To teach the science teacher'],1,'Она хотела увереннее говорить по-английски.'],
['What was wrong with the first recording?',['It sounded rushed and lacked expression','It contained no information','It was recorded outside','It used several languages'],0,'Её голос звучал монотонно и торопливо.'],
['What did Amir suggest?',['Reading even faster','Removing the deadline','Using more complex vocabulary','Imagining a conversation with a friend'],3,'Он предложил представить, что она объясняет всё одному другу.'],
['Why did they keep a pause?',['The microphone had failed','The episode was too short','To draw attention to important information','To hide a mistake'],2,'Пауза перед сроком регистрации помогала слушателям обратить на него внимание.'],
['What did Sofia do before publication?',['Cancelled the fair','Verified and corrected a date','Removed all instructions','Invited every student personally'],1,'Она сверила дату с учителем и исправила её в сценарии.'],
['What did Sofia learn?',['Clear communication matters more than flawless delivery','Fast speech is always more persuasive','Simple language cannot sound serious','Every pause should be removed'],0,'Главное — помочь слушателю понять мысль, а не говорить идеально без пауз.'] ]},
{title:'A garden on the roof',tag:'Environment · Article',text:`The roof of a town office building once contained only pipes and grey concrete. It now holds a small garden, created by staff and local volunteers. The beds are shallow and filled with lightweight soil because an engineer advised that ordinary deep beds would be too heavy for the structure. Plants were chosen for their ability to survive wind and dry periods.

The project began as an attempt to make the building more comfortable in summer. Volunteers placed temperature sensors under the planted section and under an uncovered section nearby. On sunny afternoons, the surface beneath the plants was usually cooler. However, the team has not yet measured whether the garden reduces the building's total energy use.

The garden has brought other benefits. Staff use it for quiet breaks, and insects visit the flowers. Maintenance has been more demanding than expected, especially when several volunteers are away at the same time. A shared timetable now ensures that someone checks the plants regularly.

Other building owners have asked for advice. The organisers welcome the interest but warn against simply copying their design. Roof strength, access and local weather must be considered first. They describe the garden as one promising experiment, not a solution that can be placed on every building without careful planning.`,q:[
['Why was lightweight soil used?',['To make flowers brighter','Because ordinary soil was unavailable','To limit the weight on the roof','To avoid planting anything'],2,'Инженер предупредил, что глубокие обычные грядки будут слишком тяжёлыми.'],
['Which conditions influenced plant selection?',['Snow throughout the year','Constant shade indoors','Salt water','Wind and dry weather'],3,'Выбрали растения, устойчивые к ветру и сухим периодам.'],
['What did the sensors show?',['A cooler surface under plants on sunny afternoons','A reduction in all electricity bills','No difference at any time','Higher temperatures in every office'],0,'Измеряли температуру поверхности: под растениями она обычно была ниже.'],
['What has not yet been established?',['Whether staff visit the roof','Whether total energy use has decreased','Whether flowers attract insects','Whether a timetable exists'],1,'Общее энергопотребление здания ещё не измеряли в связи с садом.'],
['Why was a shared timetable introduced?',['To schedule public concerts','To prevent anyone taking breaks','To organise regular plant care','To replace all the sensors'],2,'График нужен, чтобы растения регулярно проверяли, даже когда часть волонтёров отсутствует.'],
['What is the organisers’ advice to others?',['Copy every detail exactly','Ignore local weather','Use deeper beds on every roof','Assess the conditions before starting'],3,'Сначала нужно оценить прочность крыши, доступ и климат.'] ]},
{title:'What a review cannot tell you',tag:'Digital life · Opinion',text:`When choosing a language course, many people begin by reading online reviews. A high average rating can be reassuring, but it does not answer every important question. A course that suits someone preparing for a university lecture may be less useful for a traveller who wants to practise everyday conversations.

The details within reviews often matter more than the stars. One reviewer may praise a teacher for correcting every error, while another finds the same approach discouraging. Neither description has to be dishonest. The two learners may simply have different goals or prefer different kinds of feedback. Knowing what you need helps you interpret their experiences.

It is also worth noticing when a review was written. A detailed account from several years ago might describe teachers who no longer work there. Recent reviews can be more relevant, although a single recent complaint should not automatically outweigh a consistent pattern of positive feedback. Repeated, specific observations are generally more informative than a dramatic statement with no explanation.

Reviews are therefore a starting point, not a complete decision. Before enrolling, a learner can ask about class size, lesson content and opportunities to speak. If a sample lesson is available, it may reveal whether the teaching style fits. The best-rated course is not necessarily the best match for every person.`,q:[
['Why might a highly rated course be unsuitable?',['All ratings are invented','Its focus may not match a learner’s goals','Good courses never receive reviews','Travellers cannot study languages'],1,'Даже хороший курс может быть рассчитан на другие цели.'],
['Why can reviewers disagree about correction?',['They may prefer different feedback styles','Only one has attended a class','The teacher must have lied','Both want identical lessons'],0,'Один ученик ценит постоянные исправления, другого они обескураживают.'],
['Why should readers check a review’s date?',['Older students write shorter reviews','Dates determine the price','Old reviews always contain errors','The course staff or conditions may have changed'],3,'Давний отзыв может описывать преподавателей, которых уже нет.'],
['Which evidence does the writer find more useful?',['One unexplained dramatic claim','The longest title','Repeated, specific observations','The number of exclamation marks'],2,'Повторяющиеся конкретные наблюдения информативнее голословной эмоциональной оценки.'],
['What can a sample lesson help reveal?',['The reviewer’s identity','Whether the teaching style suits the learner','Every future exam question','The age of all students'],1,'Пробное занятие помогает понять, подходит ли стиль обучения.'],
['What is the purpose of the article?',['To explain how to use reviews thoughtfully','To advertise one course','To show that reviews should never be read','To rank language schools'],0,'Автор объясняет, как осмысленно оценивать отзывы в контексте своих целей.'] ]}
],
[
{title:'The team’s new role',tag:'School life · Personal story',text:`When Daniel injured his ankle before the regional basketball competition, he assumed his season was over. He could not train with the team for several weeks, and watching from the side made him feel useless. His coach suggested that he help analyse their practice games instead.

At first, Daniel recorded only how many points each player scored. The coach asked him to look more closely at what happened before a successful shot. He began noting passes, movement and occasions when a player created space for someone else. He discovered that one teammate who rarely scored often made the decisions that allowed others to do so.

Daniel prepared a short presentation for the team. Rather than criticise individuals, he showed examples of combinations that worked well. Some players were surprised by his observations, and they began practising those patterns more deliberately. Daniel could not prove that his analysis alone caused their improvement, but the coach said it had helped them discuss teamwork more clearly.

When he returned to training, Daniel still enjoyed scoring. Yet he paid more attention to creating opportunities for others. He had originally seen his temporary role as a poor substitute for playing. By the end of the season, he considered it a different kind of participation that had made him a more thoughtful player.`,q:[
['Why did Daniel stop training temporarily?',['He moved away','He disliked the coach','He injured his ankle','He joined another team'],2,'Тренировки пришлось прервать из-за травмы лодыжки.'],
['What did he first record?',['Travel expenses','Practice attendance','Players’ heights','Points scored by each player'],3,'Сначала он считал только набранные очки.'],
['What did the coach encourage him to examine?',['Actions leading to successful shots','Only the final score','The audience’s behaviour','Other schools’ budgets'],0,'Тренер предложил смотреть на действия перед удачным броском.'],
['What surprised him about one teammate?',['He refused to pass','He contributed greatly without scoring much','He never attended practice','He wanted to become a coach'],1,'Игрок редко забивал, но создавал другим возможности.'],
['What does Daniel acknowledge about the improvement?',['It was entirely his achievement','It was unrelated to practice','He cannot attribute it solely to his analysis','It happened before his injury'],2,'Даниэль не может доказать, что улучшение вызвал только его анализ.'],
['How did his attitude change?',['He decided to stop playing forever','He became interested only in statistics','He thought teamwork was unnecessary','He valued contributions beyond scoring'],3,'Он начал ценить создание возможностей для других, а не только собственные очки.'] ]},
{title:'Letters for the future',tag:'Culture · Article',text:`A town archive has invited residents to write letters describing an ordinary day in their lives. The letters will be stored for twenty years before a selection is displayed in an exhibition. Organisers hope the collection will show future readers how people lived, rather than simply list the major events already recorded in newspapers.

The invitation asks writers to include small details: how they travel, what they cook and which sounds they hear from their windows. There is no prize for the most impressive story. A description of waiting for a bus may be just as useful to a future historian as an account of a public celebration.

Residents can submit handwritten letters or typed copies. Staff will make digital scans, but the paper versions will also be preserved. Contributors choose whether their names may appear in the future exhibition. Letters containing sensitive information about other people will be reviewed before any public display, and some material may remain available only for restricted research.

The archive has received many letters from older residents, but fewer from young people. To broaden the collection, staff are arranging workshops with local schools and youth groups. Their aim is not to create a perfectly complete picture of the town, which would be impossible, but to preserve a wider range of everyday experiences than official records usually contain.`,q:[
['What is the main aim of the project?',['To preserve accounts of everyday life','To replace all newspapers','To choose the town’s best writer','To publish every letter immediately'],0,'Архив хочет сохранить повседневный опыт жителей для будущего.'],
['When will a selection be displayed?',['Next week','After one year','In twenty years','Only after every resident participates'],2,'Часть писем покажут на выставке через двадцать лет.'],
['Which type of detail is encouraged?',['Only national political events','Ordinary routines and surroundings','Private information about neighbours','Invented adventures'],1,'Просят писать о поездках, еде и звуках за окном — обычных деталях жизни.'],
['What choice do contributors have?',['Whether to destroy official records','Which letters others submit','The exhibition’s exact opening date','Whether their names may be displayed'],3,'Авторы выбирают, можно ли указывать их имена на будущей выставке.'],
['Why are school workshops being arranged?',['To teach professional archivists','To increase younger people’s participation','To replace older residents’ letters','To judge a writing competition'],1,'От молодёжи пришло мало писем, и архив хочет расширить её участие.'],
['What does the final paragraph acknowledge?',['Official records include every personal experience','Young people cannot write useful accounts','The collection cannot represent the town completely','Only handwritten letters are reliable'],2,'Создать абсолютно полную картину города невозможно; цель — более широкий набор историй.'] ]},
{title:'The trouble with an average',tag:'Ideas · Data literacy',text:`A local newspaper reported that the average journey to work in Bellford had become five minutes shorter. The headline sounded like good news for every commuter. Yet some residents said their journeys had become longer. How could both statements be true?

The transport team explained that an average combines many different experiences into one number. A new express train had greatly reduced travel time for passengers living near two stations. Meanwhile, road repairs had delayed bus services in another part of town. The large improvement for one group was enough to reduce the overall average even though another group was worse off.

There was another complication. The two surveys had not involved exactly the same people. In the later survey, more respondents worked from offices near the town centre. Their shorter routes might have influenced the result independently of any transport improvements. This did not make the survey worthless, but it limited what could confidently be concluded from it.

In its next report, the team presented journey times by area and type of transport as well as an overall figure. It also explained how participants had been selected. The extra detail made the report less suitable for a simple headline, but more useful for planning services. Averages can reveal a broad pattern; they cannot, on their own, describe what has happened to everyone.`,q:[
['What did the newspaper report?',['Every commuter saved five minutes','The average commute had shortened','Bus journeys had all improved','Nobody travelled by train'],1,'Сообщалось об уменьшении среднего времени поездки, а не времени каждого человека.'],
['Why did some bus passengers have longer journeys?',['Road repairs caused delays','They all moved house','The express train stopped running','The survey required longer routes'],0,'Дорожные работы задерживали автобусные маршруты.'],
['How could the average fall while some journeys worsened?',['Averages only include buses','The newspaper removed all long journeys','The figures were necessarily false','Large gains for one group outweighed losses for another'],3,'Сильное улучшение у одной группы перевесило ухудшение у другой при расчёте среднего.'],
['What complicated comparison of the surveys?',['They used no numbers','They were both conducted on trains','The groups of respondents differed','Everyone worked in the same office'],2,'Состав опрошенных изменился: во втором опросе больше людей работало ближе к центру.'],
['What was added to the next report?',['Only a shorter headline','Results broken down by area and transport type','Names of all commuters','A claim that everyone benefited'],1,'Данные разделили по районам и видам транспорта и пояснили выбор участников.'],
['What is the main conclusion?',['An average needs context to be interpreted well','Averages should never be calculated','Every survey must interview the same people forever','Transport reports should avoid detail'],0,'Среднее показывает общую картину, но для понимания нужны контекст и различия между группами.'] ]}
]
);
const setNames=['New connections','New perspectives','Small discoveries','Better questions','Finding your voice','Beyond the obvious'];
